

platform :ios, '12.0'
install! 'cocoapods', :disable_input_output_paths => true
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
#source 'git@bitbucket.org:bluecodemobilesdk/specs.git'
use_frameworks!
target 'IDnow SDK Demo' do
	 
	pod 'ReactiveCocoa'

	pod 'KeychainAccess'
	pod 'SwiftyBeaver'
	pod 'OpenTok'
	pod 'Anyline', '5'
	 
	 
	pod 'SwiftGen'
	pod 'SwiftLint'
	pod 'Fabric'
	pod 'Crashlytics'
	 
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
	pod 'FirebaseDynamicLinks'
	
	 
	pod 'IDnowSDK'
	pod 'SCTqrScanner'
	 
end

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = '4.2'
end
end
end